```python
InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
Assign requires shapes of both tensors to match. lhs shape= [2596,300] rhs shape= [2540,300]
```
遇到上述情况请检查 当前输入的word2id 是否和 训练这个的模型时用的word2id 一致。